using System.Collections.Generic;
using UnityEngine;


public class KitchenUtensilGroup: MonoBehaviour
{
    [Header("Option")]
    [SerializeField] private ERestaurantFloorType _floorType;
    public ERestaurantFloorType FloorType => _floorType;

    [Space]
    [Header("Components")]
    [SerializeField] private KitchenUtensil[] _kitchenUtensils;
    [SerializeField] private GameObject[] _smokeAnimations;

    [Space]
    [Header("UI Options")]
    [SerializeField] private RectTransform _burnerTimerParent;
    [SerializeField] private UIBurnerTimer _burnerTimerPrefab;
    [SerializeField] private Transform[] _burnerTimerTrs;

    [Space]
    [Header("Transforms")]
    [SerializeField] private Transform _defaultChef1Pos;
    [SerializeField] private Transform _defaultChef2Pos;
    [SerializeField] private Transform _door1;
    [SerializeField] private Transform _door2;


    private UIBurnerTimer[] _burnerTimers;
    private KitchenBurnerData[] _burnerDatas;
    private Dictionary<KitchenUtensilType, List<KitchenUtensil>> _kitchenUtensilDic = new Dictionary<KitchenUtensilType, List<KitchenUtensil>>();
    private List<BurnerKitchenUtensil> _burnerKitchenUtensils = new List<BurnerKitchenUtensil>();
    private Queue<CookingData> _cookingQueue = new Queue<CookingData>();
    private SinkKitchenUtensil _sinkKitchenUtensil;

    public List<KitchenBurnerData> GetCookingBurnerDataList()
    {
        List<KitchenBurnerData> dataList = new List<KitchenBurnerData>();
        for(int i = 0, cnt = _burnerDatas.Length; i < cnt; ++i)
        {
            if (!_burnerDatas[i].IsUsable || _burnerDatas[i].CookingData.IsDefault() || _burnerDatas[i].IsStaffUsable)
                continue;

            dataList.Add(_burnerDatas[i]);
        }

        return dataList;
    }

    public SinkKitchenUtensil GetSinkKitchenUtensil()
    {
        return _sinkKitchenUtensil;
    }



    public Vector2 GetStaffPos(EquipStaffType type)
    {
        switch (type)
        {
            case EquipStaffType.Chef:
                return _defaultChef1Pos.position;
            //case EquipStaffType.Chef2:
                //return _defaultChef2Pos.position;
        }

        Debug.LogError("Į÷æų Į¾·ł °ŖĄĢ Ąßøų ĄŌ·ĀµĒ¾ś½Ą“Ļ“Ł:" + type);
        return new Vector2(0, 0);
    }

    public Vector3 GetDoorPos(Vector3 pos)
    {
        if (Mathf.Abs(_door1.position.y - pos.y) < 2)
            return _door1.position;

        else if (Mathf.Abs(_door2.position.y - pos.y) < 2)
            return _door2.position;

        return Vector3.zero;
    }

    public void Init()
    {   
        // Burner“Ā 5°³ (Burner1~Burner5, enum ĄĪµ¦½ŗ 0~4)
        int burnerCount = (int)KitchenUtensilType.Burner5 + 1;
        _burnerDatas = new KitchenBurnerData[burnerCount];
        _burnerTimers = new UIBurnerTimer[burnerCount];
        
        // Burner µ„ĄĢÅĶ ĆŹ±āČ­
        for (int i = 0; i < burnerCount; ++i)
        {
            _burnerDatas[i] = new KitchenBurnerData();
            _burnerTimers[i] = Instantiate(_burnerTimerPrefab, _burnerTimerParent);
            _burnerTimers[i].Init();
            _burnerTimers[i].SetWorldTransform(_burnerTimerTrs[i]);
            _burnerTimers[i].SetFillAmount(0);
            _burnerTimers[i].gameObject.SetActive(false);
            _smokeAnimations[i].gameObject.SetActive(false);
        }

        // KitchenUtensil µń¼Å³Źø® ĆŹ±āČ­
        for (int i = 0, cnt = (int)KitchenUtensilType.Length; i < cnt; ++i)
        {
            _kitchenUtensilDic.Add((KitchenUtensilType)i, new List<KitchenUtensil>());
        }

        // øšµē KitchenUtensil ĆŹ±āČ­ ¹× µń¼Å³Źø®æ” Ćß°”
        for (int i = 0, cnt = _kitchenUtensils.Length; i < cnt; ++i)
        {
            _kitchenUtensils[i].Init(_floorType);
            KitchenUtensilType type = _kitchenUtensils[i].Type;
            _kitchenUtensilDic[type].Add(_kitchenUtensils[i]);
            
            // Burner ÅøĄŌĄĢøé BurnerKitchenUtensil ø®½ŗĘ®æ” Ćß°” ¹× µ„ĄĢÅĶ ¼³Į¤
            if(type >= KitchenUtensilType.Burner1 && type <= KitchenUtensilType.Burner5)
            {
                BurnerKitchenUtensil burner = (BurnerKitchenUtensil)_kitchenUtensils[i];
                if (burner != null)
                {
                    int burnerIndex = (int)type; // Burner1=0, Burner2=1, ..., Burner5=4
                    _burnerKitchenUtensils.Add(burner);
                    _burnerDatas[burnerIndex].SetKitchenUtensil(_kitchenUtensils[i]);
                    burner.SetData(_burnerDatas[burnerIndex]);
                }
            }
        }

        _burnerDatas[0].IsUsable = true; // Burner1Ąŗ ±āŗ»Ąø·Ī »ēæė °”“É
        _sinkKitchenUtensil = (SinkKitchenUtensil)_kitchenUtensilDic[KitchenUtensilType.Sink][0];
        UpdateKitchen();
        UserInfo.OnChangeKitchenUtensilHandler += OnChangeKitchenUtensilEvent;
    }


    void Update()
    {
        if (!UserInfo.IsFloorValid(UserInfo.CurrentStage, _floorType))
            return;

        for (int i = 0, cnt = _burnerDatas.Length; i < cnt; ++i)
        {
            if (!_burnerDatas[i].IsUsable)
                continue;

            if (_burnerDatas[i].Time <= 0)
            {
                DequeueFood(i);
                continue; // returnĄĢ ¾Ę“Ń continue·Ī ŗÆ°ę - “ŁĄ½ ¹ö³Źµµ Ć¼Å©ĒŲ¾ß ĒŌ
            }

            // æäø® ĮßĄĪ µ„ĄĢÅĶ°” ĄÖ“Ā °ęæģ
            if (!_burnerDatas[i].CookingData.IsDefault())
            {
                if (_burnerDatas[i].CookingData.TableData == null || _burnerDatas[i].CookingData.TableData.CurrentCustomer == null)
                {
                    DequeueFood(i);
                    continue; // returnĄĢ ¾Ę“Ń continue·Ī ŗÆ°ę
                }

                float subTime = Time.deltaTime * GameManager.Instance.GetCookingSpeedMul(_floorType, _burnerDatas[i].CookingData.FoodData.FoodType) * (1 + _burnerDatas[i].AddCookSpeedMul * 0.01f * (_burnerDatas[i].UseStaff != null ? _burnerDatas[i].UseStaff.SpeedMul : 1));
                
                // _burnerKitchenUtensils ø®½ŗĘ®ĄĒ ĄĪµ¦½ŗ°” iæĶ ĄĻÄ”ĒĻ“ĀĮö Č®ĄĪ
                if (i < _burnerKitchenUtensils.Count && _burnerKitchenUtensils[i] != null)
                {
                    subTime *= _burnerKitchenUtensils[i].CookSpeedMul;
                }
                
                if (_burnerDatas[i].FoodType == _burnerDatas[i].CookingData.FoodData.FoodType)
                {
                    subTime *= 1.1f; // °°Ąŗ Ą½½Ä ÅøĄŌĄĻ ¶§“Ā 10% “õ ŗüø£°Ō æäø®
                }
                
                _burnerDatas[i].Time -= subTime;
                _burnerTimers[i].SetFillAmount(1 - (_burnerDatas[i].Time / _burnerDatas[i].CookingData.CookTime));
            }
        }
    }


    public void EqueueFood(CookingData foodData)
    {
        _cookingQueue.Enqueue(foodData);
    }


    private void DequeueFood(int burnerIndex)
    {
        if (!_burnerDatas[burnerIndex].CookingData.IsDefault())
        {
            UserInfo.AddCookCount(_burnerDatas[burnerIndex].CookingData.FoodData.Id);
            _burnerDatas[burnerIndex].CookingData.OnCompleted?.Invoke();
        }

        if (_cookingQueue.Count == 0)
        {
            ResetBurnerData(burnerIndex);
            return;
        }

        CookingData cookingData = _cookingQueue.Dequeue();
        _burnerDatas[burnerIndex].CookingData = cookingData;
        _burnerDatas[burnerIndex].Time = cookingData.CookTime;
        _burnerTimers[burnerIndex].SetActive(true);
        _smokeAnimations[burnerIndex].gameObject.SetActive(true);
        _burnerTimers[burnerIndex].SetFillAmount(0);
        _burnerTimers[burnerIndex].SetImage(cookingData.FoodData.ThumbnailSprite);
    }

    private void UpdateKitchen()
    {
        KitchenUtensilData equipData;
        KitchenUtensilType type;
        for (int i = 0, cnt = (int)KitchenUtensilType.Length; i < cnt; ++i)
        {
            type = (KitchenUtensilType)i;
            equipData = UserInfo.GetEquipKitchenUtensil(UserInfo.CurrentStage, _floorType, type);
            
            // ĒŲ“ē ÅøĄŌĄĒ øšµē KitchenUtensilæ” µ„ĄĢÅĶ ¼³Į¤
            foreach (KitchenUtensil data in _kitchenUtensilDic[type])
            {
                data.SetData(equipData);
            }

            // Burner ÅøĄŌĄĪ °ęæģ Ćß°” Ć³ø®
            if (type >= KitchenUtensilType.Burner1 && type <= KitchenUtensilType.Burner5)
            {
                int burnerIndex = (int)type; // Burner1=0, Burner2=1, ..., Burner5=4
                _burnerDatas[burnerIndex].SetFoodType(equipData != null ? equipData.FoodType : FoodType.None);
                
                // Burner2~5“Ā Ąåŗń°” ĄÖ¾ī¾ß »ēæė °”“É
                if (type >= KitchenUtensilType.Burner2)
                {
                    if (equipData != null)
                    {
                        _burnerDatas[burnerIndex].IsUsable = true;
                    }
                    else
                    {
                        _burnerDatas[burnerIndex].IsUsable = false;
                        SetDefalutBurnerData(burnerIndex);
                    }
                }
            }
        }
        CheckSink();
    }


    private void OnChangeKitchenUtensilEvent(ERestaurantFloorType floorType, KitchenUtensilType type)
    {
        if (_floorType != floorType)
            return;

        KitchenUtensilData equipData = UserInfo.GetEquipKitchenUtensil(UserInfo.CurrentStage, floorType, type);
        
        // ĒŲ“ē ÅøĄŌĄĒ øšµē KitchenUtensilæ” µ„ĄĢÅĶ ¼³Į¤
        foreach (KitchenUtensil data in _kitchenUtensilDic[type])
        {
            data.SetData(equipData);
        }

        // Burner ÅøĄŌĄĪ °ęæģæ”øø Ć³ø®
        if (type >= KitchenUtensilType.Burner1 && type <= KitchenUtensilType.Burner5)
        {
            int burnerIndex = (int)type; // Burner1=0, Burner2=1, ..., Burner5=4
            _burnerDatas[burnerIndex].SetFoodType(equipData != null ? equipData.FoodType : FoodType.None);

            // Burner2~5“Ā Ąåŗń°” ĄÖ¾ī¾ß »ēæė °”“É
            if (type >= KitchenUtensilType.Burner2)
            {
                if (equipData == null)
                {
                    _burnerDatas[burnerIndex].IsUsable = false;
                    SetDefalutBurnerData(burnerIndex);
                }
                else
                {
                    _burnerDatas[burnerIndex].IsUsable = true;
                }
            }
        }
        
        CheckSink();
    }

    private void ResetBurnerData(int index)
    {
        _burnerDatas[index].Time = 0;
        _burnerDatas[index].CookingData.SetDefault();
        _burnerTimers[index].SetFillAmount(0);
        _burnerTimers[index].SetActive(false);
        _smokeAnimations[index].gameObject.SetActive(false);
    }

    private void SetDefalutBurnerData(int index)
    {
        if (!_burnerDatas[index].CookingData.IsDefault())
        {
            _cookingQueue.Enqueue(_burnerDatas[index].CookingData);
        }
        ResetBurnerData(index);
    }

    
    private void CheckSink()
    {
        KitchenUtensilData data = UserInfo.GetEquipKitchenUtensil(UserInfo.CurrentStage, _floorType, KitchenUtensilType.Sink);
        if (data == null)
        {
            UserInfo.SetMaxSinkBowlCount(UserInfo.CurrentStage, _floorType, ConstValue.DEFAULT_MAX_BOLW_COUNT);
            return;
        }
        KitchenUtensilSinkData sinkData = (KitchenUtensilSinkData)data;
        UserInfo.SetMaxSinkBowlCount(UserInfo.CurrentStage, _floorType, sinkData.MaxSinkBowlCount);
    }


    private void OnDestroy()
    {
        UserInfo.OnChangeKitchenUtensilHandler -= OnChangeKitchenUtensilEvent;
    }
}
